// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.woodpigeon.b3.schema.v100



object V100Proto extends _root_.com.trueaccord.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.com.trueaccord.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.woodpigeon.b3.schema.v100.Payload,
    com.woodpigeon.b3.schema.v100.Update,
    com.woodpigeon.b3.schema.v100.NoteList,
    com.woodpigeon.b3.schema.v100.AddNote,
    com.woodpigeon.b3.schema.v100.PutProduct,
    com.woodpigeon.b3.schema.v100.DeleteProduct,
    com.woodpigeon.b3.schema.v100.PutStock,
    com.woodpigeon.b3.schema.v100.PutImage
  )
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CiNzaGFyZWQvc3JjL21haW4vcHJvdG9idWYvdjEwMC5wcm90bxIYY29tLndvb2RwaWdlb24uYjMuc2NoZW1hIkUKB1BheWxvY
  WQSOgoHdXBkYXRlcxgBIAMoCzIgLmNvbS53b29kcGlnZW9uLmIzLnNjaGVtYS5VcGRhdGVSB3VwZGF0ZXMifAoGVXBkYXRlEhAKA
  3JlZhgBIAEoCVIDcmVmEhgKB3ZlcnNpb24YAiABKA1SB3ZlcnNpb24SPQoHYWRkTm90ZRgHIAEoCzIhLmNvbS53b29kcGlnZW9uL
  mIzLnNjaGVtYS5BZGROb3RlSABSB2FkZE5vdGVCBwoFaW5uZXIiIAoITm90ZUxpc3QSFAoFbm90ZXMYASADKAlSBW5vdGVzIh0KB
  0FkZE5vdGUSEgoEbm90ZRgBIAEoCVIEbm90ZSI+CgpQdXRQcm9kdWN0EhwKCXByb2R1Y3RJZBgBIAEoCVIJcHJvZHVjdElkEhIKB
  G5hbWUYAiABKAlSBG5hbWUiLQoNRGVsZXRlUHJvZHVjdBIcCglwcm9kdWN0SWQYASABKAlSCXByb2R1Y3RJZCIoCghQdXRTdG9ja
  xIcCglwcm9kdWN0SWQYASABKAlSCXByb2R1Y3RJZCI4CghQdXRJbWFnZRIaCghlbnRpdHlJZBgBIAEoCVIIZW50aXR5SWQSEAoDd
  XJsGAIgASgJUgN1cmxiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}